version: '3.8'

services:
  api:
    build:
      context: backend/
    container_name: api
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure
  frontend:
    build:
      context: .
    container_name: frontend
    volumes:
      - ./frontend:/code/frontend
    ports:
      - 8000:8000
    deploy:
      restart_policy:
        condition: on-failure
  docs:
    image: python:slim
    container_name: docs
    volumes:
      - ./docs/index.html:/index.html
      - ./docs/openapi.yml:/openapi.yml
    ports:
      - 5332:8080
    command: python -m http.server 8080
    deploy:
      restart_policy:
        condition: on-failure
