version: '3.8'

services:
  api:
    image: slavatidika/api
    container_name: api
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - RUNTIME_MODE=release
    env_file:
      .env
    depends_on:
      - db
  frontend:
    image: slavatidika/frontend
    container_name: frontend
    environment:
      - ENV_MODE=PROD
    volumes:
      - ./frontend:/code/frontend
    ports:
      - 8000:3000
    deploy:
      restart_policy:
        condition: on-failure
  docs:
    image: python:slim
    container_name: docs
    volumes:
      - ./docs/index.html:/index.html
      - ./docs/openapi.yml:/openapi.yml
    ports:
      - 5332:8080
    command: python -m http.server 8080
    deploy:
      restart_policy:
        condition: on-failure
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - /var/slavatidika:/var/lib/postgresql/data/
