CREATE TABLE IF NOT EXISTS users (
       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       email varchar(255) UNIQUE NOT NULL,
       nickname varchar(45) NOT NULL,
       password varchar(100) NOT NULL
);
CREATE TYPE rarity AS ENUM ('common', 'rare', 'epic', 'legendary');
CREATE TYPE category AS ENUM ('armor', 'weapon', 'pet', 'skin');
CREATE TABLE IF NOT EXISTS items (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) UNIQUE NOT NULL,
    image_src varchar(255) UNIQUE NOT NULL,
    image_for_hero varchar(255) UNIQUE NOT NULL,
    description text NOT NULL,
    price int NOT NULL,
    item_category category NOT NULL,
    item_rarity rarity NOT NULL,
    armor int NOT NULL,
    damage int NOT NULL
);
CREATE TYPE states AS ENUM ('equipped', 'inventoried', 'store');
CREATE TABLE IF NOT EXISTS inventory (
    user_id int,
    item_id int,
    item_state states DEFAULT 'store',
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (item_id) REFERENCES items (id)
);
CREATE TYPE status AS ENUM ('active', 'completed', 'archived');
CREATE TABLE IF NOT EXISTS tasks (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id int REFERENCES users,
	name varchar(255) NOT NULL,
	description text,
	created_on timestamp(3) NOT NULL,
	due_date timestamp(3) NOT NULL,
	schtirlich_humorescue text,
	labels text,
	cur_status status NOT NULL DEFAULT 'active'
);