package db

import (
	"database/sql"

	_ "github.com/lib/pq"
)

var db *sql.DB
var err error

func init() {
	db, err = sql.Open("postgres", "host=localhost port=5432 user=postgres"+
		" dbname=slavatidika password=example sslmode=disable")
	if err != nil {
		return
	}

	_, err = db.Exec(`
DROP TABLE IF EXISTS users;
CREATE TABLE users (
       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       email varchar(255) UNIQUE NOT NULL,
       nickname varchar(20) NOT NULL,
       password varchar(100) NOT NULL
);
INSERT INTO users(email, nickname, password)
VALUES('test@example.com', 'test', 'Test123Test');
`)
}

func New() (*sql.DB, error) {
	return db, err
}
