name: Frontend

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
        paths:
          - "frontend/**"
          - "package.json"
          - "package-lock.json"
          - ".prettierrc"
          - "yarn.lock"

jobs:
    linting:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Staring Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Restoring Yarn cache
              uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Bootstraping packages
              if: steps.yarn-cache.outputs.cache-hit != 'true'
              run: yarn install

            - name: Get specific changed files
              id: changed-files
              uses: tj-actions/changed-files@v23.1
              with:
                files: |
                  **/*.html
                  **/*.css
                  **/*.js
                  **/*.ts

            - name: Echo file changes
              id: hello
              run: |
                  echo Added files: ${{ steps.changed-files.outputs.added_files }}
                  echo Changed files: ${{ steps.changed-files.outputs.modified_files }}
                  echo Removed files: ${{ steps.changed-files.outputs.deleted_files }}

            - name: Prettier Checking
              if: ${{ always() && (steps.changed-files.outputs.added_files || steps.changed-files.outputs.modified_files) }}
              run: yarn prettier --config ./frontend/prettier.config.js --ignore-path ./frontend/.prettierignore  ${{ steps.changed-files.outputs.modified_files }} ${{ steps.changed-files.outputs.deleted_files }} --fix

            - name: ESLint Checking
              if: ${{ always() && (steps.changed-files.outputs.added_files || steps.changed-files.outputs.modified_files) }}
              run: yarn eslint --config ./frontend/.eslintrc.js --ignore-path ./frontend/.eslintignore ${{ steps.changed-files.outputs.modified_files }} ${{ steps.changed-files.outputs.deleted_files }} --fix

            - name: Commit changes
              if: always()
              uses: stefanzweifel/git-auto-commit-action@v4.1.2
              with:
                  commit_message: Apply formatting changes
#           branch: ${{ github.head_ref }}
