name: Frontend

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
        paths:
          - "frontend/**"
          - "package.json"
          - "package-lock.json"
          - ".prettierrc"
          - "yarn.lock"

jobs:
    linting:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Staring Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Restoring Yarn cache
              uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Bootstraping packages
              if: steps.yarn-cache.outputs.cache-hit != 'true'
              run: yarn install

            - name: Get all file changes
              id: changed-files
              uses: tj-actions/changed-files@v23.1
              with:
                files: |
                  **/*.js
                  **/*.ts

            - name: Echo file changes
              id: hello
              run: |
                  echo Added files: ${{ steps.changed-files.outputs.added_files }}
                  echo Changed files: ${{ steps.changed-files.outputs.modified_files }}
                  echo Removed files: ${{ steps.changed-files.outputs.deleted_files }}

            - name: Get changed JavaScript files
              id: changed-files-js
              uses: tj-actions/changed-files@v23.1
              with:
                files: |
                  **/*.js
            
            - name: Prettier Checking
              if: ${{ always() && (steps.changed-files-js.outputs.added_files || steps.changed-files-js.outputs.modified_files) }}
              run: yarn prettier --config ./frontend/prettier.config.cjs --ignore-path ./frontend/.prettierignore  ${{ steps.changed-files-js.outputs.modified_files }} ${{ steps.changed-files-js.outputs.added_files }} -w

            - name: ESLint Checking
              if: ${{ always() && (steps.changed-files-js.outputs.added_files || steps.changed-files-js.outputs.modified_files) }}
              run: yarn eslint --config ./frontend/.eslintrc.cjs --ignore-path ./frontend/.eslintignore ${{ steps.changed-files-js.outputs.modified_files }} ${{ steps.changed-files-js.outputs.added_files }} --fix

            - name: Get changed TypeScript files
              id: changed-files-ts
              uses: tj-actions/changed-files@v23.1
              with:
                files: |
                  **/*.ts

            - name: Get all TypeScript files
              id: files-ts
              uses: Rishabh510/Path-lister-action@master
              with:
                path: "frontend/js/"
                type: ".ts"
            
            - name: Prettier Checking
              if: ${{ always()  && (steps.changed-files-ts.outputs.added_files || steps.changed-files-ts.outputs.modified_files) }}
              run: yarn prettier --config ./frontend/prettier.config.cjs --ignore-path ./frontend/.prettierignore  ${{ steps.changed-files-ts.outputs.modified_files }} ${{ steps.changed-files-ts.outputs.added_files }} -w
            - name: TsLint Checking
              if: ${{ always() && (steps.changed-files-ts.outputs.added_files || steps.changed-files-ts.outputs.modified_files) }} 
              run: yarn tsc -t es6 --noEmit ${{ steps.files-ts.outputs.paths }}

            - name: Get all HTML files changes
              id: changed-files-html
              uses: tj-actions/changed-files@v23.1
              with:
                files: |
                  **/*.html

            - name: Get all HTML files
              id: files-html
              uses: Rishabh510/Path-lister-action@master
              with:
                path: "frontend/html/"
                type: ".html"

            - name: Prettier Checking
              if: ${{ always() && (steps.changed-files-html.outputs.added_files || steps.changed-files-html.outputs.modified_files) }}
              run: yarn prettier --config ./frontend/html/prettier.config.cjs --ignore-path ./frontend/.prettierignore  ${{ steps.changed-files-html.outputs.modified_files }} ${{ steps.changed-files-html.outputs.added_files }} -w

            - name: Commit changes
              if: always()
              uses: stefanzweifel/git-auto-commit-action@v4.1.2
              with:
                  commit_message: Apply formatting changes
                  branch: ${{ github.head_ref }}
